import Link from "next/link";
import PageHeader from "@/components/admin/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getAdminArticlePosts } from "@/lib/content/articles";
const PostsPage = async () => {
    const posts = await getAdminArticlePosts();
    const published = posts.filter((post) => post.status === "published").length;
    return <><PageHeader eyebrow="Content" title="Posts" description="Create, review, and manage every article in your publication." action={<Button asChild><Link href="/admin/posts/new"><span className="icon-[lucide--plus] size-4"/>Add post</Link></Button>}/><div className="mb-4 flex flex-wrap gap-2"><Badge variant="outline">{posts.length} total</Badge><Badge variant="outline">{published} published</Badge><Badge variant="outline">{posts.length - published} drafts</Badge></div><Card><CardHeader><CardTitle>All posts</CardTitle><CardDescription>Draft and published content ordered by the latest update.</CardDescription></CardHeader><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Post</TableHead><TableHead>Taxonomy</TableHead><TableHead>Status</TableHead><TableHead>Engagement</TableHead><TableHead>Updated</TableHead><TableHead className="pr-6 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{posts.map((post) => <TableRow key={post.slug}><TableCell className="pl-6"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-md bg-muted text-muted-foreground"><span className="icon-[lucide--file-text] size-4"/></span><div><p className="font-medium text-foreground">{post.title}</p><p className="mt-0.5 max-w-xs truncate text-xs text-muted-foreground">/{post.slug}</p></div></div></TableCell><TableCell className="text-muted-foreground">{post.category}{post.subcategory ? ` / ${post.subcategory}` : ""}</TableCell><TableCell><Badge variant={post.status === "published" ? "default" : "secondary"}>{post.status}</Badge></TableCell><TableCell className="text-muted-foreground"><span className="inline-flex items-center gap-1"><span className="icon-[lucide--eye] size-3.5"/>{post.views}</span><span className="mx-2">·</span><span className="inline-flex items-center gap-1"><span className="icon-[lucide--thumbs-up] size-3.5"/>{post.usefulCount}</span></TableCell><TableCell className="text-muted-foreground">{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(post.updatedAt))}</TableCell><TableCell className="pr-6 text-right"><Button asChild variant="outline" size="sm"><Link href={`/admin/posts/${post.slug}/edit`}><span className="icon-[lucide--pencil] size-3.5"/>Edit</Link></Button></TableCell></TableRow>)}</TableBody></Table>{posts.length === 0 ? <div className="grid place-items-center px-6 py-14 text-center"><span className="icon-[lucide--files] mb-3 size-9 text-muted-foreground"/><p className="font-medium text-foreground">No posts found</p><p className="mt-1 text-sm text-muted-foreground">Your articles will appear here after you create them.</p><Button asChild size="sm" className="mt-4"><Link href="/admin/posts/new">Create your first post</Link></Button></div> : null}</CardContent></Card></>;
};
export default PostsPage;
